version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/lab/jenkins:/var/jenkins_home
    networks:
      - lab_net

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - /home/ec2-user/lab/sonarqube/data:/opt/sonarqube/data
      - /home/ec2-user/lab/sonarqube/extensions:/opt/sonarqube/extensions
      - /home/ec2-user/lab/sonarqube/logs:/opt/sonarqube/logs
      - /home/ec2-user/lab/sonarqube/temp:/opt/sonarqube/temp
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonarqube_db
    networks:
      - lab_net

  sonarqube_db:
    image: postgres:alpine
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - /home/ec2-user/lab/postgresql/data:/var/lib/postgresql/data
    networks:
      - lab_net

networks:
  lab_net:
    driver: bridge

