- name: Build & Deploy Docker container
  hosts: dockerServers
  vars:
    project_dir: /home/ec2-user/paymob-tech-task
    dest_project_dir: /home/ec2-user
    image_name: paymob-java-app
  remote_user: ec2-user
  tasks:
    - name: Copy pipeline project dir to docker host
      tags:
        - skip_this_task
      copy:
        src: "{{ project_dir }}"
        dest: "{{ dest_project_dir }}"
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        build: 
          path: "{{ project_dir }}"
        source: build
    - name: Create Docker Container
      community.docker.docker_container:
        name: "{{ image_name }}"
        image: "{{ image_name }}"
        state: started
      notify:
        - Capture container creation1
        - Capture container creation2
        - Output list of container creations
  

  handlers:
    - name: Capture container creation1
      ansible.builtin.command: docker ps -a --format "table {{'{{'}}.Names{{'}}'}}\t{{'{{'}}.CreatedAt{{'}}'}}"
      register: created_containers
    - name: Capture container creation2
      ansible.builtin.shell: docker ps -a --format "table {{'{{'}}.Names{{'}}'}}\t{{'{{'}}.CreatedAt{{'}}'}}" >> /home/ec2-user/result.txt
    - name: Output list of container creations
      ansible.builtin.debug:
        var: created_containers.stdout_lines
